const palavras = [
    "abacate", "abacaxi", "abelha", "abanador", "antologia", "amor", "aba", "abrigo", "abrir",
    "banana", "boi", "batata", "bacalhau", "bexiga", "bowl", "batedeira", "bisturi", "barreira", "banco",
    "caixa", "chantilly", "cachorro", "cuidado", "caneta", "carinho", "cabra", "cesto",
    "dados", "dizer", "danone", "dente", "diamante", "diafragma", "detonar", "dia",
    "elefante", "esmeralda", "esfinge", "esfera", "encontro", "ema", "escola", "economia",
    "formiga", "fama", "festa", "fiador", "ferver", "flauta", "figo", "fiapo", "fotografia",
    "goiaba", "gelo", "grito", "guria", "goleiro", "golfinho", "golfe", "girar",
    "harmonia", "haste", "hectare", "hepatite", "hiena", "hidrante",
    "igreja", "importante", "idoso", "irado", "identidade", "idioma", "idade", "idiota",
    "jantar", "jumento", "jararaca", "janela", "jerimum", "jaula", "jabuti", "jaleco",
    "laranja", "lua", "luz", "lindo", "lacraia", "lactose", "lacrar",
    "manga", "morango", "mico", "matar", "mingau", "moqueca", "mocassin",
    "nectarina", "nada", "navio", "namorado", "ninja", "natal", "narciso", "narina", "nabo",
    "ovo", "ostra", "obstetra", "orangotango", "olhar", "ortodoxo", "ouro", "ornamento",
    "pato", "polvo", "povoar", "pano", "princesa", "pizza", "patroa",
    "queijo", "quitanda", "quinta", "quantia", "quarentena", "quadrilha", "quaresma", "quartzo", "quebrar",
    "risada", "rio", "remar", "rato", "racional", "rainha", "radioatividade", "raiz", "raiva", "rachadura",
    "salada", "salamandra", "sacola", "siri", "sabre", "sucarose", "sabedoria", "sacerdote",
    "tatu", "tabacaria", "taberneiro", "torrada", "tamanho", "tatuagem", "trem",
    "uva", "universo", "unanimidade", "ubuntu", "universidade", "urso", "uivar", "unir",
    "vela", "valeta", "vacilo", "valor", "vagem", "vadiagem", "vaca", "valentia", "vidro", "valsa",
    "xadrez", "xilofone", "xarope", "xenofobia", "xereta", "xerife", "xaveco", "xixi", "xale",
    "zebra", "zagueiro", "zero", "zoeira", "zepelim", "zinco", "zumbido", "álbum", "fácil", "réptil", "éden", "ímpar", "vírus", "sótão", "tórax", "túnel", "júri", "sofá", "crachá", "parabéns",
    "jacarés", "açaí", "cipós", "dominó", "baú", "plástico", "gráfico", "espécie", "célebre", "míope",
    "líquido", "próximo", "fósforo", "último", "público", "imprescindível", "aurélio", "dicionário", "cônjuge",
    "resiliência", "recíproco", "intrínseco", "efêmero", "cínico", "caráter", "anuência", "diligência",
    "ninfomaníaca", "condolências", "intempérie", "idôneo", "contemporâneo", "escrúpulo", "supérfluo", "idílico",
    "âmbito", "análogo", "genuíno", "propósito", "essência", "hipócrita", "parcimônia", "misógino", "estória",
    "implícito", "viés", "néscio", "índole", "referência", "complacência", "corolário", "âmago", "pêsames",
    "peremptório", "empírico", "família", "característica", "inexorável", "inócuo", "êxito", "pragmático", "convém",
    "condescendência", "esdrúxulo", "apático", "discrepância", "hermético", "concupiscência", "perspicácia",
    "altruísmo", "altruísta", "arbitrário", "lascívia","extraordinário", "prodígio", "passível", "sádico",
    "astúcia", "aleatório", "audácia", "promíscuo", "pródigo", "circunstância", "déspota", "híbrido",
    "divergência", "contíguo", "indivíduo", "controvérsia", "veemência", "influência", "coerência", "profícuo",
    "congruência", "princípio","autoritário", "herói", "sistêmico", "criança", "justiça", "cabeça", "açúcar",
    "ambição", "coração", "paçoca", "confiança", "mudança", "engraçado", "convicção",
    "abraço", "açaí", "doçura", "almoço", "bênção", "quiçá", "caçula", "muçulmano", "exceção",
    "peça", "cansaço", "preço", "maciço", "preguiça", "crença", "canção", "espaço", "serviço",
    "endereço", "açucareiro", "ranço", "alvoroço", "cachaça", "sumiço", "solução", "graça", "começo"
]

export default palavras